# Base configs
baseurl: ""
url: "http://geografa.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "YOUMAKEBEAUTIFULTHINGS"
subtitle: "Do not fear mistakes. There are none. - Miles Davis"
author: "Rafa Gutierrez"
bio: "I am a carto/photo/grapher from Portland, Oregon, USA."
design: "<a href=\"https://github.com/ramswaroop/photography\"> on github</a>."
social_urls:
  facebook: "https://www.facebook.com/rafa.gutierrez"
  twitter: "https://www.twitter.com/geografa"
  instagram: "https://www.instagram.com/geografa"
  linkedin: "https://in.linkedin.com/in/rafaelgutierrez1"
  github: "https://www.github.com/geografa"
  